---
title: "Codebook for the data"
author: "Elina Lutz"
date: "01/06/2021"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = FALSE  # whether or not to show R code
)
ggplot2::theme_set(ggplot2::theme_bw())
```

```{r prepare_codebook}
if (!require(pacman)) install.packages("pacman")
pacman::p_load(data.table, codebook, labelled, sjlabelled, dplyr)

# preparation
data <- fread("../processed/data.csv")

# VAR_LABEL --------------------------------------------------------------------
var_label(data$id) <- "Participant id"
var_label(data$startdate) <- "Date and time the participant started"
var_label(data$enddate) <- "Date and time the participant finished"
var_label(data$progress) <- "How far the participant progressed in the study"
var_label(data$duration_seconds) <- "How long the participant took for the study (in seconds)"
var_label(data$finished) <- "If the participant finished the study"
var_label(data$userlanguage) <- "The language in which the participant processed the study"

# seek_risk
var_label(data$seek_risk_general) <- "How do you rate yourself personally? Are you generally a risk-taker or do you try to avoid risks?"
var_label(data$seek_risk_health) <- "How would you rate your risk tolerance in relation to the following areas? How about your health?"
# I'm not too happy about the "how about"
var_label(data$seek_risk_data) <- "How would you rate your risk tolerance in relation to the following areas? How about the disclosure of personal data?"
var_label(data$seek_risk_econ) <- "How would you rate your risk tolerance in relation to the following areas? How about investments?"

# svo
var_label(data$svo_1) <- "Social value orientation according to Murphy et al. (2011)"
var_label(data$svo_2) <- "Social value orientation according to Murphy et al. (2011)"
var_label(data$svo_3) <- "Social value orientation according to Murphy et al. (2011)"
var_label(data$svo_4) <- "Social value orientation according to Murphy et al. (2011)"
var_label(data$svo_5) <- "Social value orientation according to Murphy et al. (2011)"
var_label(data$svo_6) <- "Social value orientation according to Murphy et al. (2011)"

# iwah_close
var_label(data$iwah_close_1) <- "How close do you feel to each of the following groups? - People in my community"
var_label(data$iwah_close_2) <- "How close do you feel to each of the following groups? - Swiss people"
var_label(data$iwah_close_3) <- "How close do you feel to each of the following groups? - People all over the world"

# iwah_ref
var_label(data$iwah_ref_1) <- "How often do you use the word 'we' to refer to the following groups? - People in my community"
var_label(data$iwah_ref_2) <- "How often do you use the word 'we' to refer to the following groups? - Swiss people"
var_label(data$iwah_ref_3) <- "How often do you use the word 'we' to refer to the following groups? - People all over the world"

# iwah_common
var_label(data$iwah_common_1) <- "How many things do you have in common with the following groups? - People in my community"
var_label(data$iwah_common_2) <- "How many things do you have in common with the following groups? - Swiss people"
var_label(data$iwah_common_3) <- "How many things do you have in common with the following groups? - People all over the world"

# iwah_family -> spelling mistake, can/should this be corrected?
var_label(data$iwah_familiy_1) <- "Sometimes people count other people as family, even if they are not actually part of their own family. How much do you count the following groups as family? - People in my community"
var_label(data$iwah_familiy_2) <- "Sometimes people count other people as family, even if they are not actually part of their own family. How much do you count the following groups as family? - Swiss people"
var_label(data$iwah_familiy_3) <- "Sometimes people count other people as family, even if they are not actually part of their own family. How much do you count the following groups as family? - People all over the world"

# iwah_identify
var_label(data$iwah_identify_1) <- "How much do you identify with (feel part of, love, care about) each of the following groups? - People in my community"
var_label(data$iwah_identify_2) <- "How much do you identify with (feel part of, love, care about) each of the following groups? - Swiss people"
var_label(data$iwah_identify_3) <- "How much do you identify with (feel part of, love, care about) each of the following groups? - People all over the world"

# iwah_care
var_label(data$iwah_care_1) <- "How much do you care (have compassion, want to help) when bad things happen to the following groups?  - People in my community"
var_label(data$iwah_care_2) <- "How much do you care (have compassion, want to help) when bad things happen to the following groups?  - Swiss people"
var_label(data$iwah_care_3) <- "How much do you care (have compassion, want to help) when bad things happen to the following groups?  - People all over the world"

# iwah_responsibility
var_label(data$iwah_responsibility_1) <- "How much do you wish you were the following? - A responsible citizen of my community"
var_label(data$iwah_responsibility_2) <- "How much do you wish you were the following? - A responsible citizen of Switzerland"
var_label(data$iwah_responsibility_3) <- "How much do you wish you were the following? - A responsible citizen of the world"

# iwah_loyalty
var_label(data$iwah_loyalty_1) <- "How much do you think the following statements apply to you? - Being loyal to my community"
var_label(data$iwah_loyalty_2) <- "How much do you think the following statements apply to you? - Being loyal to Switzerland"
var_label(data$iwah_loyalty_3) <- "How much do you think the following statements apply to you? - Being loyal to all people"

# iwah_help
var_label(data$iwah_help_1) <- "How much would you like to help members of the following groups when they need help? - People in my community"
var_label(data$iwah_help_2) <- "How much would you like to help members of the following groups when they need help? - Swiss people"
var_label(data$iwah_help_3) <- "How much would you like to help members of the following groups when they need help? - People all over the world"

# honesty-humility personality
var_label(data$honhum_lies) <- "Please indicate how much you agree with the following statements. - Lying is difficult for me."
var_label(data$honhum_makemoney) <- "Please indicate how much you agree with the following statements. - I would like to know how to make a lot of money illegally."
var_label(data$honhum_celebrity) <- "Please indicate how much you agree with the following statements. - I want to be famous."
var_label(data$honhum_special) <- "Please indicate how much you agree with the following statements. - I deserve special treatment."

# check1
var_label(data$check1_correct3) <- "Please indicate how much you agree with the following statements. - This question is used to record whether the questionnaire is being processed attentively. Please answer 'Neutral' here."

# technology
var_label(data$tech_general) <- "The next questions are about how you deal with new technologies and smartphones. Do you try out new technical things in general?"
var_label(data$has_smartphone) <- "Do you own a smartphone?"
var_label(data$tech_interest_apps) <- "Do you install new applications/apps on your smartphone?"
var_label(data$tech_interest_ability) <- "Do you find it easy to use a new application/app for your smartphone?"

# health
var_label(data$is_infected) <- "Do you yourself or someone you are in close contact with have a confirmed infection with the new coronavirus at the moment?"
var_label(data$was_infected) <- "Have you yourself or someone with whom you are in close contact had a confirmed infection with the new coronavirus?"

var_label(data$has_symptoms_fever) <- "Have you had the following symptoms in the past two weeks (14 days)? - Fever"
var_label(data$has_symptoms_feverfeel) <- "Have you had the following symptoms in the past two weeks (14 days)? - Fever sensation"
var_label(data$has_symptoms_sorethroat) <- "Have you had the following symptoms in the past two weeks (14 days)? - Sore throat"
var_label(data$has_symptoms_drycough) <- "Have you had the following symptoms in the past two weeks (14 days)? - Dry cough"
var_label(data$has_symptoms_shortbreath) <- "Have you had the following symptoms in the past two weeks (14 days)? - Shortness of breath"
var_label(data$has_symptoms_muscleache) <- "Have you had the following symptoms in the past two weeks (14 days)? - Muscle ache"
var_label(data$has_symptoms_nosense) <- "Have you had the following symptoms in the past two weeks (14 days)? - Sudden loss of the sense of smell and/or taste"

# mental health
var_label(data$mhealth_irritable) <- "Please think about the last month (the last 30 days). - How many times in the last month were you upset because something unexpected happened?"
var_label(data$mhealth_control) <- "Please think about the last month (the last 30 days). - How many times in the last month did you feel that you were not able to control the important things in your life?"
var_label(data$mhealth_nervous) <- "Please think about the last month (the last 30 days). - How many times in the last month have you felt nervous and stressed?"
var_label(data$mhealth_cope) <- "Please think about the last month (the last 30 days). - How many times in the last month have you felt like you were not up to all of your upcoming tasks?"
var_label(data$mhealth_anger) <- "Please think about the last month (the last 30 days). - How many times in the last month have you been angry about things you had no control over?"
var_label(data$mhealth_difficulty) <- "Please think about the last month (the last 30 days). - How many times in the last month have you felt like so many difficulties have piled up that you could not overcome them?"

# policy attitudes
var_label(data$attitudes_policies) <- "The next questions refer to the measures against the spread of the new coronavirus in Switzerland. - Are the measures taken by the federal government correct?"
var_label(data$attitudes_civilrights) <- "The next questions refer to the measures against the spread of the new coronavirus in Switzerland. - Are the measures taken by the federal government an excessive intrusion on fundamental rights?"

# check2
var_label(data$check2_correct1) <- "The next questions refer to the measures against the spread of the new coronavirus in Switzerland. - This question is used to record whether the questionnaire is being processed attentively. Please answer 'Disagree completely' here."

# acceptance
var_label(data$acc_use) <- "The following questions deal with your personal attitude towards the SwissCovid app. - Will you use the SwissCovid app? (If you already use the SwissCovid app, please select 'Agree completely')."
var_label(data$acc_convince) <- "The following questions deal with your personal attitude towards the SwissCovid app. - Will you try to convince other people to use the SwissCovid app?"
var_label(data$acc_important) <- "The following questions deal with your personal attitude towards the SwissCovid app. - Do you think the SwissCovid app will help contain the spread of the coronavirus?"
var_label(data$acc_trust) <- "The following questions deal with your personal attitude towards the SwissCovid app. - Do you think the data collected by the SwissCovid app are safe?"

# compliance
var_label(data$com_isolation) <- "Please imagine that you are using the SwissCovid app. The following questions deal with your interaction with the SwissCovid app. - Would you put yourself into voluntary self-isolation if the SwissCovid app notifies you that you have been in contact with a person who has tested positive?"
var_label(data$com_hotline) <- "Please imagine that you are using the SwissCovid app. The following questions deal with your interaction with the SwissCovid app. - Would you call the specified hotline if the SwissCovid app notifies you that you have been in contact with a person who has tested positive?"
var_label(data$com_report) <- "Please imagine that you are using the SwissCovid app. The following questions deal with your interaction with the SwissCovid app. - Would you enter your own infection into the SwissCovid app if you had contracted the coronavirus?"
var_label(data$com_test) <- "Please imagine that you are using the SwissCovid app. The following questions deal with your interaction with the SwissCovid app. - Would you make an effort to get yourself tested for the new coronavirus if the SwissCovid app notified you that you had been in contact with someone who tested positive?"

# risk knowledge and risk perception
var_label(data$know_infected_all_ab) <- "How many people in Switzerland have been infected with the coronavirus since the beginning of the corona crisis?"
var_label(data$know_death_total) <- "How many people in Switzerland have died from infection with the coronavirus since the beginning of the corona crisis?"

var_label(data$perc_infected_last7) <- "Now we are no longer talking about the total number of people affected in Switzerland, but about the risk of being newly infected within a week, based on 100,000 people. How likely is a new infection in 7 days? Imagine two times 100,000 randomly selected people in Switzerland. - How many people have been newly infected with the coronavirus in the past 7 days (out of 100,000 randomly selected people in Switzerland)?"
var_label(data$perc_infected_next7) <- "How many people will become newly infected with the coronavirus in the next 7 days (out of 100,000 randomly selected people in Switzerland)?"
var_label(data$perc_moneyloss) <- "How many workers out of 100 will lose more than half their income in the next few months?"
var_label(data$perc_data) <- "How many out of 100 users of the SwissCovid app will unintentionally publish personal data?"
var_label(data$perc_severe) <- "How many out of 100 people infected with the coronavirus develop a severe course of the disease caused by the virus?"

var_label(data$know_econ) <- "How high do you estimate the economic costs of the new coronavirus for Switzerland? (In billions of CHF. For information: the GDP of Switzerland in 2019 was CHF 699 billion.)"
var_label(data$know_age) <- "Age is a risk factor for severe courses. At what age does the risk for a severe course increase?"
var_label(data$know_symptoms) <- "Which of the following pre-existing conditions favor a severe course of the disease caused by the virus? Please tick all the answers that apply. 1 = Gastrointestinal diseases, 2 = Diseases and therapies that weaken the immune system, 3 = Chronic respiratory diseases, 4 = High blood pressure, 5 = Diseases of the liver, 6 = Cancer, 7 = Diabetes, 8 = Cardiovascular diseases, 9 = Nervous disorders (neurological disorders), 10 = Diseases of the kidneys"

# safety behavior
var_label(data$safety_mask) <- "In the last 7 days, how often did you wear a mouth-nose protection in situations where it would have been advisable?"
var_label(data$safety_distance) <- "In the last 7 days, how often did you keep a distance of at least 1.5 meters from other people in public life in situations where it would have been advisable to do so?"
var_label(data$safety_hygene) <- "In the last 7 days, how often did you use a tissue or, if not available, the crook of your arm when coughing or sneezing?"

# vaccination
var_label(data$vacc_self) <- "The following questions address your personal attitude toward vaccination against Covid-19, a disease caused by coronavirus - Will you get vaccinated against Covid-19 when a vaccine is available?"
var_label(data$vacc_others) <- "The following questions address your personal attitude toward vaccination against Covid-19, a disease caused by coronavirus - Will you try to convince other people to get vaccinated against Covid-19?"
var_label(data$vacc_work) <- "The following questions address your personal attitude toward vaccination against Covid-19, a disease caused by coronavirus - Do you think that comprehensive vaccination can lead to herd immunity, thereby eradicating Covid-19?"
var_label(data$vacc_gen) <- "The following questions address your personal attitude toward vaccination against Covid-19, a disease caused by coronavirus - In general, do you think vaccinations are important?"

# moderator variables
var_label(data$raw_belief_efficiency) <- "The following questions deal with your personal assessment of the SwissCovid app. - Do you think that enough people will use the SwissCovid app?"
var_label(data$belief_5) <- "The following questions deal with your personal assessment of the SwissCovid app. - Do you think the SwissCovid app works well enough technically?"
var_label(data$raw_belief_local) <- "The following questions deal with your personal assessment of the SwissCovid app. - Is the new coronavirus a problem for your immediate neighborhood including yourself?"
var_label(data$raw_belief_global) <- "The following questions deal with your personal assessment of the SwissCovid app. - Is the new coronavirus a problem for the whole world?"

# check3
var_label(data$check3_correct5) <- "The following questions deal with your personal assessment of the SwissCovid app. - This question is used to record whether the questionnaire is being processed attentively. Please answer 'Agree completely' here."

# comprehension
var_label(data$comprehension_data) <- "Which of the following statements are correct about the functionality of the SwissCovid app? - When using the SwissCovid app, all data is stored anonymously."
var_label(data$comprehension_self) <- "Which of the following statements are correct about the functionality of the SwissCovid app? - When I use the SwissCovid app, it helps me stay healthy."
var_label(data$comprehension_other) <- "Which of the following statements are correct about the functionality of the SwissCovid app? - When I use the SwissCovid app, I help other people stay healthy."
var_label(data$comprehension_severe) <- "Which of the following statements are correct about the functionality of the SwissCovid app? - When I use the SwissCovid app, I help people from risk groups stay healthy."

# demographics
var_label(data$age) <- "How old are you?"
var_label(data$female) <- "What is your biological sex?"
var_label(data$education) <- "What is your highest educational qualification?"
var_label(data$household) <- "How many people live with you in your household? If you live alone, enter 0."
var_label(data$community) <- "Approximately how many inhabitants live in the place where you live at the moment? - Selected Choice"
var_label(data$community_1_text) <- "Approximately how many inhabitants live in the place where you live at the moment? - Text"
var_label(data$community_cat) <- "Can you give us an approximate size? Approximately how many inhabitants live in the place where you live?"
var_label(data$household_kids) <- "How many of the people living with you in your household are under 18?"
var_label(data$income_num) <- "What is your monthly income, excluding any losses due to the corona crisis (after taxes, in francs)? - Selected Choice"
var_label(data$income_num_1_text) <- "What is your monthly income, excluding any losses due to the corona crisis (after taxes, in francs)? - Text"
var_label(data$wealth_num) <- "How high are your assets (in Swiss francs)? - Selected Choice"
var_label(data$wealth_num_1_text) <- "How high are your assets (in Swiss francs)? - Text"
var_label(data$had_work) <- "Were you employed (self-employed or dependent) prior to the corona crisis in 2020?"
var_label(data$has_work) <- "Are you currently employed (self-employed or dependent)?"
var_label(data$income_cat) <- "In which category does your monthly income fall (before taxes, in francs), excluding any losses due to the corona crisis?"
var_label(data$wealth_cat) <- "In which category do your assets fall approximately (in francs)?"
var_label(data$income_loss) <- "Do you have a lower income from your job due to the corona crisis?"
var_label(data$homeoffice) <- "Are you working in home office at the moment?"

var_label(data$data_quality) <- "Did you fill out the questionnaire in a concentrated way so that we can use your data?"

# other variables
var_label(data$sc0) <- ""
var_label(data$u) <- ""
var_label(data$c) <- ""

var_label(data$perc_risk_severe) <- ""
var_label(data$perc_risk_data) <- ""
var_label(data$perc_risk_econ) <- ""

var_label(data$community_imputed) <- ""
var_label(data$income_imputed) <- ""
var_label(data$wealth_imputed) <- ""

var_label(data$know_symptoms_perc) <- ""
var_label(data$raw_know_age) <- ""
var_label(data$raw_know_infected_all_ab) <- ""
var_label(data$raw_know_death_total) <- ""

var_label(data$accept_index) <- ""
var_label(data$comply_index) <- ""
var_label(data$vaccine_index) <- ""

var_label(data$honhum_score) <- ""
var_label(data$perc_risk_health) <- ""

var_label(data$iwah_community) <- ""
var_label(data$iwah_swiss) <- ""
var_label(data$iwah_world) <- ""
var_label(data$iwah_diff_score) <- ""

var_label(data$svo_angle) <- ""
var_label(data$policy_score) <- ""
var_label(data$mhealth_score) <- ""
var_label(data$tech_score) <- ""
var_label(data$compreh_score) <- ""
var_label(data$has_symptoms) <- ""
var_label(data$know_health_score) <- ""
var_label(data$safebehavior_score) <- ""



# VALUE_LABELS -----------------------------------------------------------------
# short cuts
risk_preference <- c("Not at all willing to take risks" = 0, 
                     "Very willing to take risks" = 10)

disagree_agree <- c("Disagree completely" = 1,
                    "Rather disagree" = 2,
                    "Neutral" = 3,
                    "Rather agree" = 4,
                    "Agree completely" = 5)

notatall_very <- c("Not at all" = 1, 
                   "Only little" = 2,
                   "A bit" = 3,
                   "Quite" = 4,
                   "Very" = 5)

no_yes <- c("No" = 0,
            "Yes" = 1)

never_veryoften <- c("Never" = 1, 
                     "Almost never" = 2,
                     "Sometimes" = 3,
                     "Quite often" = 4,
                     "Very often" = 5)

perc_outof100000 <- c("Up to 5 out of 100,000" = 2, 
                   "6-10 out of 100,000" = 8,
                   "11-15 out of 100,000" = 13,
                   "16-20 out of 100,000" = 18, 
                   "21-25 out of 100,000" = 23,
                   "26-30 out of 100,000" = 28,
                   "31-35 out of 100,000" = 33,
                   "36-40 out of 100,000" = 38,
                   "41-45 out of 100,000" = 42,
                   "Over 45 out of 100,000" = 46)

perc_outof100 <- c("Up to 5 out of 100" = 11, 
                "6-10 out of 100" = 12,
                "11-15 out of 100" = 13,
                "16-20 out of 100" = 14, 
                "21-25 out of 100" = 15,
                "26-30 out of 100" = 16,
                "31-35 out of 100" = 17,
                "36-40 out of 100" = 18,
                "41-45 out of 100" = 19,
                "Over 45 out of 100" = 20)

# metadata
val_labels(data$finished) <- no_yes

# risk_preference
val_labels(data[, c("seek_risk_general", "seek_risk_health", "seek_risk_data", "seek_risk_econ")]) <- risk_preference

# iwah
val_labels(data[, c("iwah_close_1", "iwah_close_2", "iwah_close_3")]) <- c("Not at all close" = 1,
                                                                           "Rather not close" = 2,
                                                                           "Somewhat close" = 3,
                                                                           "Rather close" = 4,
                                                                           "Very close" = 5)

val_labels(data[, c("iwah_ref_1", "iwah_ref_2", "iwah_ref_3")]) <- c("Almost never" = 1,
                                                                     "Rarely" = 2,
                                                                     "Sometimes" = 3,
                                                                     "Often" = 4,
                                                                     "Very often" = 5)

val_labels(data[, c("iwah_common_1", "iwah_common_2", "iwah_common_3")]) <- c("Almost none" = 1,
                                                                              "Only a few" = 2,
                                                                              "Some" = 3,
                                                                              "Quite a few" = 4,
                                                                              "A lot" = 5)


val_labels(data[, c("iwah_familiy_1", "iwah_familiy_2", "iwah_familiy_3",
                    "iwah_identify_1", "iwah_identify_2", "iwah_identify_3",
                    "iwah_care_1", "iwah_care_2", "iwah_care_3",
                    "iwah_responsibility_1", "iwah_responsibility_2", "iwah_responsibility_3",
                    "iwah_loyalty_1", "iwah_loyalty_2", "iwah_loyalty_3",
                    "iwah_help_1", "iwah_help_2", "iwah_help_3")]) <- notatall_very
# the answer format doesn't really fit iwah_care, iwah_help, etc.

# honesty-humility personality
val_labels(data[, c("honhum_lies", "honhum_makemoney", "honhum_celebrity", 
                    "honhum_special", "check1_correct3")]) <- disagree_agree

# technology
val_labels(data[, c("tech_general", "tech_interest_apps", "tech_interest_ability")]) <- disagree_agree

# technology & health
val_labels(data[, c("has_smartphone", "is_infected", "was_infected",
                    "has_symptoms_fever", "has_symptoms_feverfeel", "has_symptoms_sorethroat",
                    "has_symptoms_drycough", "has_symptoms_shortbreath",
                    "has_symptoms_muscleache", "has_symptoms_nosense")]) <- no_yes

# mental health
val_labels(data[, c("mhealth_irritable", "mhealth_control", "mhealth_nervous",
                    "mhealth_cope", "mhealth_anger", "mhealth_difficulty")]) <- never_veryoften

# policy attitudes
val_labels(data[, c("attitudes_policies", "attitudes_civilrights", "check2_correct1")]) <- disagree_agree

# acceptance
val_labels(data[, c("acc_use", "acc_convince", "acc_important", "acc_trust")]) <- disagree_agree

# compliance
val_labels(data[, c("com_isolation", "com_hotline", "com_report", "com_test")]) <- disagree_agree

# risk knowledge & risk perception
val_labels(data$know_infected_all_ab) <- c("Up to 5,000" = 2500, 
                                           "5,001-10,000" = 7500,
                                           "10,001-15,000" = 12500,
                                           "15,001-20,000" = 17500, 
                                           "20,001-25,000" = 22500,
                                           "25,001-30,000" = 27500,
                                           "30,001-35,000" = 32500,
                                           "35,001-40,000" = 37500,
                                           "40,001-45,000" = 42500,
                                           "45,001-50,000" = 47500,
                                           "Over 50,000" = 47501)

val_labels(data$know_death_total) <- c("Up to 500" = 250, 
                                       "501-1,000" = 750,
                                       "1,001-1,500" = 1250,
                                       "1,501-2,000" = 1750, 
                                       "2,001-2,500" = 2250,
                                       "2,501-3,000" = 2750,
                                       "3,001-3,500" = 3250,
                                       "3,501-4,000" = 3750,
                                       "4,001-4,500" = 4250,
                                       "Over 4,500" = 4500)

val_labels(data[, c("perc_infected_last7", "perc_infected_next7")]) <- perc_outof100000

val_labels(data$perc_moneyloss) <- c("Up to 5 out of 100" = 1, 
                                    "6-10 out of 100" = 2,
                                    "11-15 out of 100" = 3,
                                    "16-20 out of 100" = 4, 
                                    "21-25 out of 100" = 5,
                                    "26-30 out of 100" = 6,
                                    "31-35 out of 100" = 7,
                                    "36-40 out of 100" = 8,
                                    "41-45 out of 100" = 9,
                                    "Over 45 out of 100" = 10)

val_labels(data[, c("perc_data", "perc_severe")]) <- perc_outof100

val_labels(data$know_econ) <- c("0-50 billion" = 1, 
                                "51-100 billion" = 2,
                                "101-150 billion" = 3, 
                                "151-200 billion" = 13,
                                "201-250 billion" = 4, 
                                "251-300 billion" = 14,
                                "301-350 billion" = 15, 
                                "351-400 billion" = 5,
                                "401-450 billion" = 6, 
                                "451-500 billion" = 7,
                                "501-550 billion" = 8, 
                                "551-600 billion" = 9,
                                "601-650 billion" = 16, 
                                "651-700 billion" = 10,
                                "Over 700 billion" = 12)

# vaccination
val_labels(data[, c("vacc_self", "vacc_others", "vacc_work", "vacc_gen")]) <- disagree_agree

# moderator variables
val_labels(data[, c("raw_belief_efficiency", "belief_5", "raw_belief_local", "raw_belief_global", "check3_correct5")]) <- disagree_agree

# comprehension
val_labels(data[, c("comprehension_data", "comprehension_self", "comprehension_other", "comprehension_severe")]) <- disagree_agree

# demographics
val_labels(data$female) <- c("Male" = 0,
                             "Female" = 1,
                             "Not specified" = 2)

val_labels(data$education) <- c("Compulsory school not completed" = 1,
                                "Compulsory school completed" = 2,
                                "Basic vocational training (Federal Certificate of Proficiency EFZ, Federal Certificate of Vocational Education and Training EBA, Commercial College, apprenticeship certificate)" = 3, 
                                "General education (Gymnasiale Matura, Berufsmatura, Fachmatura, secondary technical school diploma, international baccalaureate)" = 4, 
                                "Higher vocational education (diploma of higher vocational school, federal certificate of proficiency, federal diploma)" = 5, 
                                "University (FH/PH/UH Bachelor, Master, Doctorate)" = 6) # have Jana take a look

val_labels(data$community) <- c("I do not know" = 0,
                                "Specified (see community_1_text)" = 1)

val_labels(data$community_cat) <- c("Small village (up to 500 inhabitants)" = 1, 
                                    "Large village (up to 10,000 inhabitants)" = 2,
                                    "Small town (up to 50,000 inhabitants)" = 3, 
                                    "City (up to 100,000 inhabitants)" = 4, 
                                    "Big city (from 100,000 inhabitants)" = 5, 
                                    "I do not know" = 6)

val_labels(data$income_num) <- c("I do not want to specify" = 0,
                                "Specified (see income_num_1_text)" = 1)
val_labels(data$wealth_num) <- c("I do not want to specify" = 0,
                                "Specified (see wealth_num_1_text)" = 1) 

val_labels(data[, c("had_work", "has_work")]) <- no_yes

val_labels(data$income_cat) <- c("Up to 1,000" = 1, 
                                 "1,001-2,000" = 2,
                                 "2,001-3,000" = 3,
                                 "3,001-4,000" = 4, 
                                 "4,001-5,000" = 5,
                                 "5,001-6,000" = 6,
                                 "6,001-7,000" = 7,
                                 "7,001-8,000" = 8,
                                 "Over 8,000" = 9,
                                 "I do not want to specify" = 0)

val_labels(data$wealth_cat) <- c("0" = 1, 
                                 "1-25,000" = 2,
                                 "25,001-50,000" = 3,
                                 "50,001-100,000" = 4, 
                                 "100,001-200,000" = 5,
                                 "200,001-500,000" = 6,
                                 "500,001-1,000,000" = 7,
                                 "Over 1,000,000" = 8,
                                 "I do not want to specify" = 0)

val_labels(data$income_loss) <- no_yes

val_labels(data$homeoffice) <- c("No" = 0,
                                 "Yes" = 1,
                                 "Partly" = 2)

# data quality
val_labels(data$data_quality) <- disagree_agree

```

```{r codebook}
# CODEBOOK ---------------------------------------------------------------------
# add metadata
metadata(data)$name <- "Risk Preferences and Risk Perception Affect the Acceptance of Digital Contact Tracing"
metadata(data)$description <- "The questionnaire was given in German and for the purpose of this codebook translated into English." # add a longer description of the study
metadata(data)$identifier <- ""
metadata(data)$datePublished <- ""
metadata(data)$citation <- ""
metadata(data)$keywords <- ""
metadata(data)$temporalCoverage <- "July 2020"
metadata(data)$spatialCoverage <- "online"

metadata(data)$creator <- list(
  "@type" = "Person",givenName = "Rebecca", familyName = "Albrecht",
  "@type" = "Person",givenName = "Jana B.", familyName = "Jarecki",
  "@type" = "Person", givenName = "Dominik", familyName = "Meier",
  "@type" = "Person", givenName = "Jörg", familyName = "Rieskamp")
# is there a nicer way to present the authors?
# who is a doctor and/or professor?
# email & affiliation could be added

compact_codebook(data)
```

